language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt
before_script:
  - rm -f ./reservation/migrations/*.py
  - touch ./reservation/migrations/__init__.py
  - sed "1s/.*/HEROKU = False/" ./Clinic/settings.py > tmp; cat tmp > ./Clinic/settings.py; rm ./tmp;
  - python ./manage.py makemigrations
  - nvm install 6.2.1
  - nvm use 6.2.1
  - npm install
  - npm test
# command to run tests
script: python ./manage.py test
