# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_code',
            field=models.PositiveIntegerField(default='', error_messages={'unique': 'این شماره نظام پزشکی برای پزشک دیگری ثبت شده است.'}, unique=True),
        ),
        migrations.AlterField(
            model_name='systemuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to='reservation.Role'),
        ),
    ]
