# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('sat', 'شنبه'), ('sun', 'یک\u200cشنبه'), ('mon', 'دوشنبه'), ('tue', 'سه\u200cشنبه'), ('wed', 'چهارشنبه'), ('thu', 'پنج\u200cشنبه'), ('fri', 'جمعه')], default='شنبه', max_length=30)),
                ('range_num', models.IntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to='reservation.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('role_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservation.Role')),
            ],
            options={
                'abstract': False,
            },
            bases=('reservation.role',),
        ),
        migrations.AddField(
            model_name='office',
            name='base_time',
            field=models.IntegerField(choices=[(10, '10'), (15, '15'), (20, '20'), (30, '30'), (60, '60')], default=15),
        ),
        migrations.AddField(
            model_name='office',
            name='from_hour',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23)], null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='to_hour',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23)], null=True),
        ),
        migrations.RemoveField(
            model_name='doctorsecretary',
            name='office',
        ),
        migrations.AddField(
            model_name='doctorsecretary',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservation.Office'),
        ),
    ]
