# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 06:00
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='opening_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('sat', 'شنبه'), ('sun', 'یک\u200cشنبه'), ('mon', 'دوشنبه'), ('tue', 'سه\u200cشنبه'), ('wed', 'چهارشنبه'), ('thu', 'پنج\u200cشنبه'), ('fri', 'جمعه')], max_length=27, null=True),
        ),
    ]
