# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20161217_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='id_code',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
