# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20161221_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='cv',
            field=models.TextField(max_length=90),
        ),
    ]
