# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20161223_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='country',
        ),
        migrations.AlterField(
            model_name='office',
            name='city',
            field=models.CharField(choices=[('Tehran', 'تهران'), ('Isfahan', 'اصفهان'), ('Mahshad', 'مشهد'), ('Yazd', 'یزد'), ('Kerman', 'کرمان'), ('Rasht', 'رشت'), ('Zanjan', 'زنجان'), ('Qazvin', 'قزوین'), ('Qom', 'قم'), ('Hamedan', 'همدان'), ('Karaj', 'کرج')], default='تهران', max_length=30),
        ),
    ]
