# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20170107_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'منتظر تایید'), ('ACCEPTED', 'تایید شده'), ('REJECTED', 'رد شده')], max_length=30)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('date', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reservations', to='reservation.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reservations', to='reservation.SystemUser')),
            ],
        ),
    ]
