# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_auto_20170107_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservetimequantity',
            name='doctor',
        ),
        migrations.AddField(
            model_name='reservation',
            name='range_num',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='ReserveTimeQuantity',
        ),
    ]
